### ISSUE TITLE
Is it intended to be so slow?

### ISSUE THREAD

**Issue by kivanov82** [sacmii/rn-vertical-slider#1]
Trying it out, but the delay between the gesture and the actual change of the slider is pretty huge.
Is it intended to be so, or configurable?

**Comment by kivanov82** [comment]
Upd: love the view of it though!

**Comment by sacmii** [comment]
@kivanov82 It was intended to be so, will make it configurable

**Comment by blakeperdue** [comment]
This is super slow, but very cool. @sacmii how would we increase the feedback speed?

**Comment by pradeepkeshary-eb** [comment]
you need to replace `bottom` with an `Animated.View` component that uses `transform: translate` to position the slider

**Comment by aswin-enegotz** [comment]
working on it. will publish it soon

**Comment by 4rmx** [comment]
@blakeperdue in `Animated.timing` you can add some duration eg.
` Animated.timing(value, {
..., 
duration: 100,})
`

**Comment by sacmii** [comment]
> @blakeperdue in `Animated.timing` you can add some duration eg.
> `Animated.timing(value, { ..., duration: 100,})`

Thanks @4rmx ..
Was little busy with personal stuff.. Will rollout next Version soon.
Thanks for Supporting
