### ISSUE TITLE
can publish new version in npm ?

### ISSUE THREAD

**Issue by 97thjingba** [sacmii/rn-vertical-slider#15]
I found this rep update 16 days ago
but when i want to solve the ' useNativeDriver' 
npm version is not publish .
please update the npm version 
thankes

**Comment by KVinS** [comment]
This is still not fixed (

**Comment by sacmii** [comment]
@KVinS @97thjingba 
Sorry for the delay.
Updated NPM Version

**Comment by KVinS** [comment]
No problem. I had to write my component ...
Yours worked incorrectly in modal and there is no border width.
![Uploading 2020-05-23_17-27-25.png…]()

**Comment by sacmii** [comment]
> No problem. I had to write my component ...
> Yours worked incorrectly in modal and there is no border width.
> ![2020-05-23_17-27-25](https://user-images.githubusercontent.com/3009807/82733170-c818cb00-9d1a-11ea-9d72-026a9c20e63b.png)

thanks for notifying about border width. Will soon add it
