### ISSUE TITLE
There is something wrong ...when update to 1.1.0

### ISSUE THREAD

**Issue by 97thjingba** [sacmii/rn-vertical-slider#16]
![image](https://user-images.githubusercontent.com/39749571/82865330-0c91aa00-9f59-11ea-9dc2-7462ff62e8d3.png)

**when i try to upgrade this libraries  to 1.1.0 ...**

**Comment by 97thjingba** [comment]
I have to back to 1.0.6 ... it spend more time to solve it . finally. i found it cause by this.

**Comment by sacmii** [comment]
Please provide the steps to reproduce issue?
or @97thjingba 
may be issue with cache. did you tried to reset cache in React Native and rerun the project?

**Comment by 97thjingba** [comment]
yes. I did.
but still like this

**Comment by sacmii** [comment]
> yes. I did.
> but still like this
thanks.
It was working fine for me. I tried initialising with a new project  with react-native init

**Comment by 97thjingba** [comment]
sorry. I just want to solve ' useNativeDriver ' this warn . 
thanks for your reply .

**Comment by sacmii** [comment]
useNativeDriver  wont work with this module because, Style property 'height' is not supported by native animated module
