### ISSUE TITLE
invarient violation: Module HMRClient is not a registered callable module(calling setup)

### ISSUE THREAD

**Issue by govind1530** [sacmii/rn-vertical-slider#18]
i don't know is react native  issue or what after installing libeary it wont refresh..

**Comment by sacmii** [comment]
@govind1530 Can you provide steps to reproduce the issue

**Comment by dylancom** [comment]
I'm getting a black screen after importing VerticalSlider

`import VerticalSlider from 'rn-vertical-slider'`

**Comment by sacmii** [comment]
> I'm getting a black screen after importing VerticalSlider
> 
> `import VerticalSlider from 'rn-vertical-slider'`
> 
> Followed by the following errors:
> 
> * ExceptionsManager.js:179 Invariant Violation: Module RCTDeviceEventEmitter is not a registered callable module (calling emit)
> * ExceptionsManager.js:179 Invariant Violation: Module JSTimers is not a registered callable module (calling callTimers)
> * Invariant Violation: Module RCTDeviceEventEmitter is not a registered callable module (calling emit)

thanks for notifying. Will look into issue soon.

**Comment by danielhros** [comment]
Same problem. My screen of simulator is after importing package blank white.

**Comment by danielhros** [comment]
Is there something new going on with the issue?

**Comment by sacmii** [comment]
@danielhros @dylancom 
Sorry for delay. The issue has been fixed.
