### ISSUE TITLE
value设置成了最小值-100，最大值100  当前值0 时候的问题

### ISSUE THREAD

**Issue by jahnli** [sacmii/rn-vertical-slider#2]
为什么设置成了最小值-100，最大值100  当前值0 时候 
![image](https://user-images.githubusercontent.com/20943608/56787805-3ba68b00-6830-11e9-9367-7ab85ee37f3a.png)
需要点击一下才能变成正常位置
![image](https://user-images.githubusercontent.com/20943608/56787814-42cd9900-6830-11e9-995b-a452fb3eec5f.png)

**Comment by sacmii** [comment]
please provide steps to reproduce above result.

**Comment by harshitaahuja** [comment]
@jahnli  Were you able to find any fix?

**Comment by sacmii** [comment]
Closing this unclear issue
