### ISSUE TITLE
Component does not re-render with new value when parent is re-rendered. 

### ISSUE THREAD

**Issue by ankitgusai** [sacmii/rn-vertical-slider#23]
The initial value set with 'value' prop does work but subsequent changes in value do not rerender the component.

The demo below should be sufficient to reproduce the issue.

I am new to React Native so please correct me if I am doing something wrong.

https://snack.expo.io/@ankitgusai19/re-render-issue-rm-vertical-slider

I have checked the code a bit and to my understanding, the 'value' that is passed in the prop is not used directly, rather a different state variable 'value' is computed and used in render method. This computation is only triggered by componentDidMount()

**Comment by baselbj** [comment]
I just added a PR #24  to solve this. i you like to test you can use it like so, in package.json:
`"rn-vertical-slider": "git://github.com/baselbj/rn-vertical-slider"`

**Comment by ankitgusai** [comment]
@baselbj I since implemented this workaround, after looking at few solutions.

```
componentDidUpdate(prevProps: props) {
    // Typical usage (don't forget to compare props):
    if (this.props.value !== prevProps.value) {
      this._changeState(this.props.value);
    }
  }
``` 

I checked yours, and you are doing basically the same thing in  `shouldcomponentupdate`. 
If you can elaborate that would be very helpful.

Thanks.

**Comment by baselbj** [comment]
@ankitgusai react rerenders when props or state is updated. in this library they use the state.value in render() function not the props.value. they are using the props.value to update the state.value in _changeState() function.

this function is only called on componentDidMount and panResponder event, this means the render() function will only see the new state value on component mount and when user moves the slider. 

both componentDidUpdate or shouldcomponentupdate are fired each time the props is updated, so we can use them to update the state.

I am not a fan of component base and I don't really know which one is more performant but I used the  shouldcomponentupdate in my PR as in this function you can control not to rerender if the value is not changed. 

Hoping this clarifies it :)
