### ISSUE TITLE
Invariant Violation: [263, "RCTView",{"height": "<<NaN>> "}] is not usable as a native method argument

### ISSUE THREAD

**Issue by lochungtin** [sacmii/rn-vertical-slider#28]
Error is thrown randomly whenever the slider is touched, not dragged.
The slider also jumps to max value when touched.

![image](https://user-images.githubusercontent.com/17095177/111860978-c42ef700-8985-11eb-94bc-43aa1550f0ef.png)

Code used: (darkGrey and grey are exported constant hex values)
```
            <VerticalSlider
                borderRadius={5}
                height={275}
                maximumTrackTintColor={darkGrey}
                max={this.props.max || 255}
                minimumTrackTintColor={grey}
                min={0}
                onChange={this.props.onValueChange}
                step={1}
                value={this.props.value}
                width={32}
            />
```

**Comment by jainRashiTFT** [comment]
any solution?

**Comment by lochungtin** [comment]
the issue is caused by value being greater than the value passed in the max prop
