### ISSUE TITLE
onComplete is broken on 3.1.0

### ISSUE THREAD

**Issue by CosminPerRam** [sacmii/rn-vertical-slider#79]
React-native: 0.70.1
React-native-reanimated: 2.12.0

`onComplete` doesnt work at all (`onChange` works as expected) on `3.1.0` but on `2.0.2` works as expected.
No errors/warnings are shown on.
Changing properties during runtime also doesnt work.

**Comment by sacmii** [comment]
> React-native: 0.70.1 React-native-reanimated: 2.12.0
> 
> `onComplete` doesnt work at all (`onChange` works as expected) on `3.1.0` but on `2.0.2` works as expected. No errors/warnings are shown on. Changing properties during runtime also doesnt work.

can u provide steps for **Changing properties during runtime also doesnt work.**

**Comment by CosminPerRam** [comment]
Given that we have the following component:
```js
import VerticalSlider from 'rn-vertical-slider';

const MySlider = ({disabled}) => {
  const [value, setValue] = useState(0);
  return (
    <VerticalSlider
      value={value}
      disabled={disabled}
      onChange={(value) => setValue(value)}
      height={200}
      width={40}
      step={1}
      min={0}
      max={100}
      borderRadius={5}
      minimumTrackTintColor="#2979FF"
      maximumTrackTintColor="#D1D1D6"
      showBallIndicator
      ballIndicatorColor="#2979FF"
      ballIndicatorTextColor="#fff"
      ballIndicatorWidth={80}
      ballIndicatorHeight={40}
    />
  );
}
```

Where we use it, as, for example:
```js
const [disableRange, setDisableRange] = useState(false);
//...
<MySlider disabled={disableRange}>
//...
//somewhere we change the state with setDisableRange
```
It doesn't work.
As I said, onComplete is also broken.
Am I doing something wrong? Is this not working only for me? How could I reliably debug this?

**Comment by evanstern** [comment]
Can confirm. This is happening for me as well. `onComplete` never triggers:

```
      <VerticalSlider
        value={value}
        step={1}
        min={0}
        max={100}
        height={200}
        width={10}
        onChange={onChange}
        onComplete={onComplete}
        ballIndicatorColor="white"
        ballIndicatorWidth={25}
        ballIndicatorHeight={25}
        showBallIndicator
        ballIndicatorPosition={-7}
        minimumTrackTintColor="transparent"
        maximumTrackTintColor="transparent"
        ballIndicatorTextColor="transparent"
      />
```
